// Independent decoded flash/beep timing, not a physical display/speaker measurement or CPU benchmark.
import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {serve} from '../experiments/pipeline-qualification/server.mjs';
const server=await serve({pagePath:'tests/beta-av-page.html'}),out=`results/beta/av-sync-${new Date().toISOString().replaceAll(':','-')}`;await mkdir(out,{recursive:true});console.log(out);const result={method:'AudioWorklet beep onset mapped through getOutputTimestamp, versus rVFC white-frame expectedDisplayTime; software-clock estimate only',trials:[]};
try{for(const spec of [{variant:'native',media:'sync'},{variant:'remux',media:'sync'},{variant:'remux',media:'syncmkv'},{variant:'native',media:'edit'},{variant:'remux',media:'edit'},{variant:'native',media:'offsetmp4',offset:250},{variant:'remux',media:'offsetmp4',offset:250}]){
 const r={...spec};result.trials.push(r);const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
 try{const page=await browser.newPage();await page.goto(server.origin+'/experiment/page.html');await page.evaluate(o=>start(o),{...spec,url:server.origin+'/media/'+spec.media});r.timing=await page.evaluate(async()=>{
  await player.pause();await player.seek(0);const v=document.querySelector('video'),ctx=new AudioContext({latencyHint:'interactive'});await ctx.resume();
  const url=URL.createObjectURL(new Blob([`class Probe extends AudioWorkletProcessor{constructor(){super();this.last=-1;}process(inputs,outputs){const a=inputs[0]?.[0];if(a){for(let i=0;i<a.length;i++)if(Math.abs(a[i])>.15&&(currentFrame+i)/sampleRate-this.last>.5){this.last=(currentFrame+i)/sampleRate;this.port.postMessage(this.last);break;}for(let c=0;c<outputs[0].length;c++)outputs[0][c].set(inputs[0][c]||a);}return true;}}registerProcessor('probe',Probe);`],{type:'text/javascript'}));
  await ctx.audioWorklet.addModule(url);URL.revokeObjectURL(url);const source=ctx.createMediaElementSource(v),node=new AudioWorkletNode(ctx,'probe');source.connect(node).connect(ctx.destination);const audio=[],video=[],c=document.createElement('canvas');c.width=c.height=1;const x=c.getContext('2d',{willReadFrequently:true});let last=-1,done=false;
  node.port.onmessage=e=>{const stamp=ctx.getOutputTimestamp();audio.push({contextTime:e.data,perf:stamp.performanceTime+(e.data-stamp.contextTime)*1000});};
  const frame=(now,m)=>{x.drawImage(v,0,0,1,1);if(x.getImageData(0,0,1,1).data[0]>200&&m.mediaTime-last>.5){last=m.mediaTime;video.push({mediaTime:m.mediaTime-(player.timelineBias||0),perf:m.expectedDisplayTime});}if(!done)v.requestVideoFrameCallback(frame);};v.requestVideoFrameCallback(frame);const begun=performance.now();await player.play();await new Promise(r=>setTimeout(r,6500));done=true;await player.pause();const state=snapshot();node.disconnect();source.disconnect();await ctx.close();return {begun,audio,video,state};
 });r.deltas=r.timing.video.filter(v=>v.mediaTime>1&&v.mediaTime<5).map(v=>({mediaTime:v.mediaTime,ms:r.timing.audio.map(a=>a.perf-v.perf).filter(d=>Math.abs(d-(spec.offset||0))<400).sort((a,b)=>Math.abs(a-(spec.offset||0))-Math.abs(b-(spec.offset||0)))[0]}));assert.ok(r.deltas.length>=3);assert.ok(r.deltas.every(d=>Number.isFinite(d.ms)&&Math.abs(d.ms-(spec.offset||0))<100),'Flash/beep browser-clock alignment within 100ms');await page.evaluate(()=>stop());r.passed=true;
 }catch(e){r.error=String(e.stack);r.passed=false;process.exitCode=1;console.log(r.error.split('\n')[0]);}finally{await browser.close();await writeFile(out+'/result.json',JSON.stringify(result,null,2)+'\n');}}
}finally{await server.close();result.passed=result.trials.every(t=>t.passed);await writeFile(out+'/result.json',JSON.stringify(result,null,2)+'\n');console.log(out);}
