import {chromium, firefox} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdir, writeFile, readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out = `results/player-api/media-lab-${process.env.BROWSER || 'chrome'}-${new Date().toISOString().replaceAll(':', '-')}`;
await mkdir(out, {recursive: true}); console.log(out);
const server = spawn(process.execPath, ['scripts/serve.mjs'], {env: {...process.env, PORT: '0'}, stdio: ['ignore', 'pipe', 'inherit']});
let browser, page;
const result = {passed: false, started: new Date().toISOString(), checks: []};
const check = name => {result.checks.push(name); console.log('PASS', name);};
try {
  const origin = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('Server timeout')), 10000);
    server.once('error', error => {clearTimeout(timer); reject(error);});
    server.stdout.on('data', bytes => {const match = /http:\/\/127\.0\.0\.1:\d+/.exec(String(bytes)); if (match) {clearTimeout(timer); resolve(match[0]);}});
  });
  const expected = await readFile('fixtures/example.mp4');
  const range = await fetch(`${origin}/fixtures/example.mp4`, {headers: {Range: 'bytes=10-29'}});
  assert.equal(range.status, 206); assert.match(range.headers.get('etag'), /^"[a-f0-9]{64}"$/);
  assert.equal(range.headers.get('content-range'), `bytes 10-29/${expected.length}`);
  assert.deepEqual(Buffer.from(await range.arrayBuffer()), expected.subarray(10, 30));
  const suffix = await fetch(`${origin}/fixtures/example.mp4`, {headers: {Range: 'bytes=-10'}});
  assert.deepEqual(Buffer.from(await suffix.arrayBuffer()), expected.subarray(-10));
  const invalid = await fetch(`${origin}/fixtures/example.mp4`, {headers: {Range: 'bytes=999999999-'}});
  assert.equal(invalid.status, 416);
  const head = await fetch(`${origin}/fixtures/example.mp4`, {method: 'HEAD'});
  assert.equal(head.headers.get('content-length'), String(expected.length));
  assert.equal(head.headers.get('content-type'), 'video/mp4');
  check('Local server media types, byte ranges, validators and HEAD');
  browser = process.env.BROWSER === 'firefox' ? await firefox.launch() : await chromium.launch({channel: 'chrome', args: ['--autoplay-policy=no-user-gesture-required']});
  result.browser = browser.version();
  page = await browser.newPage({viewport: {width: 1440, height: 1100}});
  page.setDefaultTimeout(30000);
  const errors = [], unexpectedNetwork = [];
  page.on('pageerror', error => {errors.push(String(error)); console.error('PAGE ERROR', String(error));});
  page.on('request', request => {if (/^https?:/.test(request.url()) && !request.url().startsWith(origin + '/')) unexpectedNetwork.push(request.url()); if (request.method() !== 'GET') unexpectedNetwork.push(request.method());});
  await page.goto(origin); await page.waitForFunction(() => window.player);
  const idle = () => page.waitForFunction(() => !document.querySelector('#file').disabled);
  assert.equal(await page.evaluate(() => crossOriginIsolated), true);
  assert.equal(await page.locator('#mode').isDisabled(), true);
  assert.equal(await page.locator('#vf').isDisabled(), false);
  await page.screenshot({path: `${out}/desktop.png`, fullPage: true});
  check('Isolated page, automatic controls and desktop layout');
  await page.locator('#file').setInputFiles({name:'incomplete.mkv',mimeType:'video/x-matroska',buffer:Buffer.alloc(65536)}); await idle();
  assert.equal(await page.locator('#playback-error').isVisible(), true);
  assert.match(await page.locator('#playback-error-message').textContent(), /65,536 zero bytes/);
  assert.match(await page.locator('#engine-reason').textContent(), /could not be opened/);
  assert.equal(await page.locator('#engine-badge').textContent(), 'OPEN FAILED');
  assert.match(await page.locator('#engine-attempts').textContent(), /Software could not play/);
  assert.equal(await page.locator('#play').isDisabled(), true);
  assert.equal(await page.locator('#surface video,#surface canvas').count(), 0);
  await page.screenshot({path:`${out}/invalid-file.png`,fullPage:true});
  check('First-source failure is visible and retains all failed engine attempts');
  await page.locator('#file').setInputFiles('fixtures/example.mp4'); await idle();
  assert.equal(await page.locator('#playback-error').isVisible(), false);
  await page.waitForFunction(() => player.properties.get('time-pos') > .3);
  assert.equal(await page.locator('#filename').textContent(), 'example.mp4');
  assert.equal(await page.evaluate(() => player.mode), 'native');
  assert.equal(await page.locator('#audio-output').isDisabled(), true);
  check('Real local File playback with no upload');
  await page.click('#pause'); await idle();
  assert.equal(await page.evaluate(() => player.properties.get('pause')), true);
  await page.locator('#volume').fill('35'); await page.locator('#volume').dispatchEvent('change'); await idle();
  await page.selectOption('#speed', '1.5'); await idle();
  await page.locator('#timeline').fill('2'); await page.locator('#timeline').dispatchEvent('change'); await idle();
  assert.equal(await page.evaluate(() => player.properties.get('volume')), 35);
  assert.equal(await page.evaluate(() => player.properties.get('speed')), 1.5);
  assert.ok(Math.abs(await page.evaluate(() => player.properties.get('time-pos')) - 2) < .5);
  check('Pause, volume, playback speed and seek');
  await page.click('#settings-toggle');
  assert.equal(await page.locator('#settings-dialog').isVisible(), true);
  await page.screenshot({path: `${out}/settings.png`, fullPage: true});
  await page.uncheck('#automatic'); await idle();
  await page.selectOption('#mode', 'hybrid'); await idle();
  assert.equal(await page.evaluate(() => player.mode), 'hybrid');
  assert.equal(await page.locator('#text-track').isDisabled(), false);
  await page.selectOption('#mode', 'software'); await idle();
  assert.equal(await page.evaluate(() => player.mode), 'software');
  check('Manual Hybrid and Software switching');
  await page.locator('#text-track').setInputFiles('build/fixtures/compatibility/subtitle.srt'); await idle();
  assert.ok(await page.locator('#subs').textContent().then(value => value.includes('subtitle.srt')));
  await page.locator('#font').setInputFiles('build/fixtures/compatibility/custom.ttf'); await idle();
  assert.equal(await page.locator('#attachments li').count(), 2);
  check('SRT and custom font uploads through the real API');
  await page.check('#tone-map'); await idle();
  assert.equal(await page.evaluate(() => player.diagnostics.toneMapping), 'hdr-to-sdr');
  await page.uncheck('#tone-map'); await idle();
  check('HDR-to-SDR control');
  await page.click('.filters-panel summary');
  await page.fill('#vf', 'hflip'); await page.fill('#af', 'volume=0.5'); await page.click('#apply-filters'); await idle();
  assert.equal(await page.evaluate(() => player.diagnostics.videoFilters), 'hflip');
  assert.equal(await page.evaluate(() => player.diagnostics.audioFilters), 'volume=0.5');
  await page.selectOption('#mode', 'native'); await idle();
  assert.match(await page.locator('#status').textContent(), /Clear filters/);
  assert.equal(await page.inputValue('#mode'), 'software');
  await page.click('#clear-filters'); await idle();
  check('Filters and failed mode-change rollback');
  await page.click('#diagnostics-panel summary');
  const downloadPromise = page.waitForEvent('download'); await page.click('#export');
  const download = await downloadPromise;
  const report = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(report.source.name, 'example.mp4'); assert.equal(report.player.mode, 'software');
  assert.equal(report.attachments.fonts[0], 'custom.ttf');
  check('Downloadable session diagnostics');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#settings-dialog').isVisible(), false);
  assert.equal(await page.locator('#settings-toggle').evaluate(element => element === document.activeElement), true);
  check('Settings drawer closes with Escape and restores keyboard focus');
  await page.click('#close'); await idle();
  assert.equal(await page.locator('#status').textContent(), 'Closed.');
  assert.equal(await page.locator('#surface canvas,#surface video,iframe').count(), 0);
  assert.equal(await page.inputValue('#volume'), '100'); assert.equal(await page.inputValue('#speed'), '1');
  assert.equal(await page.locator('#attachments li').count(), 0);
  await page.waitForFunction(() => document.querySelector('#empty').hidden === false);
  check('Close resets controls and releases playback surfaces');
  await page.click('#settings-toggle');
  await page.selectOption('#audio-output', '7.1'); await idle();
  await page.click('#settings-close');
  assert.equal(await page.inputValue('#audio-output'), '7.1');
  await page.locator('#file').setInputFiles('build/fixtures/compatibility/channels-8.wav'); await idle();
  await page.waitForFunction(() => player.audioDiagnostics()?.outputChannels > 0);
  result.audio = await page.evaluate(() => player.audioDiagnostics());
  assert.ok([2, 8].includes(result.audio.outputChannels));
  check('Audio-only WAV and surround output with device negotiation');
  await page.click('#close'); await idle();
  const bytes = [...await readFile('fixtures/example.mp4')];
  const transfer = await page.evaluateHandle(bytes => {const data = new DataTransfer(); data.items.add(new File([new Uint8Array(bytes)], 'dropped.mp4', {type: 'video/mp4'})); return data;}, bytes);
  await page.dispatchEvent('#stage', 'drop', {dataTransfer: transfer}); await transfer.dispose(); await idle();
  assert.equal(await page.locator('#filename').textContent(), 'dropped.mp4');
  check('Drag-and-drop media');
  await page.click('.remote-panel summary'); await page.fill('#url', `${origin}/fixtures/missing.mp4`);
  await page.click('#remote button'); await idle();
  assert.equal(await page.locator('#status').evaluate(element => element.parentElement.dataset.error), 'true');
  assert.equal(await page.locator('#playback-error').isVisible(), true);
  assert.equal(await page.locator('#playback-error-source').textContent(), 'missing.mp4');
  assert.equal(await page.locator('#filename').textContent(), 'dropped.mp4');
  await page.click('#play'); await idle(); await page.waitForFunction(() => player.properties.get('time-pos') > .3);
  check('Failed source replacement keeps previous media playable');
  await page.fill('#url', `${origin}/fixtures/example.mp4`); await page.click('#remote button'); await idle();
  assert.equal(await page.locator('#filename').textContent(), 'example.mp4');
  assert.match(await page.locator('#file-meta').textContent(), /127.0.0.1/);
  check('Remote URL playback');
  await page.click('#close'); await idle(); await page.click('#demo'); await idle();
  assert.equal(await page.locator('#filename').textContent(), 'example.mp4');
  check('Included example button');
  await page.click('#close'); await idle();
  let pending;
  await page.route('**/fixtures/example.mp4', route => {pending = route;});
  await page.click('#demo');
  await page.waitForFunction(() => document.querySelector('#file').disabled && !document.querySelector('#close').disabled);
  await page.click('#close'); await idle();
  assert.ok(pending);
  await pending.fulfill({status: 200, contentType: 'video/mp4', body: await readFile('fixtures/example.mp4')});
  await page.waitForTimeout(250);
  assert.equal(await page.locator('#filename').textContent(), 'No media loaded');
  assert.equal(await page.locator('#surface video,#surface canvas').count(), 0);
  assert.equal(await page.locator('#play').getAttribute('aria-label'), 'Play');
  assert.equal(await page.locator('#play').isVisible(), true);
  assert.equal(await page.locator('#pause').isVisible(), false);
  await page.unroute('**/fixtures/example.mp4');
  check('Close cancels an opening source without a late reopen');
  await page.locator('.remote-panel').evaluate(element => element.open = false);
  await page.locator('.filters-panel').evaluate(element => element.open = false);
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: `${out}/mobile.png`, fullPage: true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await page.locator('#choose').isVisible(), true);
  assert.equal(await page.locator('.transport-row').evaluate(element => [...element.children].every(child => child.getBoundingClientRect().right <= element.getBoundingClientRect().right + 1)), true);
  await page.click('#settings-toggle');
  await page.screenshot({path: `${out}/mobile-settings.png`, fullPage: true});
  assert.equal(await page.locator('#settings-dialog').evaluate(element => element.getBoundingClientRect().width <= innerWidth), true);
  await page.click('#settings-close');
  assert.deepEqual(errors, []); assert.deepEqual(unexpectedNetwork, []);
  check('Mobile layout, no uncaught errors and no external requests or uploads');
  result.passed = true;
} catch (error) {
  result.failure = String(error.stack); console.error(error); process.exitCode = 1;
  if (page) {result.state = await page.evaluate(() => ({status: document.querySelector('#status')?.textContent, diagnostics: window.player?.diagnostics})).catch(() => null); await page.screenshot({path: `${out}/failure.png`, fullPage: true}).catch(() => {});}
} finally {
  await browser?.close(); server.kill('SIGTERM');
  result.finished = new Date().toISOString(); await writeFile(`${out}/result.json`, JSON.stringify(result, null, 2) + '\n');
}
