export const styles = `
:host{display:block;contain:layout;--webmpv-background:#121318;--webmpv-foreground:#f2f1f7;--webmpv-accent:#b7a0ff;--webmpv-border:#393941;--webmpv-radius:16px;color:var(--webmpv-foreground);font:14px/1.5 system-ui,sans-serif;color-scheme:dark}
*{box-sizing:border-box}[hidden]{display:none!important}button,input,select{font:inherit;color:inherit}button,select{background:#24242d;border:1px solid var(--webmpv-border);border-radius:9px;min-height:40px;padding:7px 12px;cursor:pointer}button:hover{background:#34333f}button:disabled,input:disabled,select:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:3px solid var(--webmpv-accent);outline-offset:3px}input[type=range]{accent-color:var(--webmpv-accent);min-height:32px;margin:0;cursor:pointer}input[type=file]{width:100%;max-width:270px}select{max-width:100%}
.shell{position:relative;background:var(--webmpv-background);border:1px solid var(--webmpv-border);border-radius:var(--webmpv-radius);overflow:clip}.stage{position:relative;display:grid;place-items:center;background:#08090c;min-height:180px;aspect-ratio:var(--media-aspect,16/9);max-height:75vh;overflow:hidden}.surface{width:100%;height:100%;position:absolute;inset:0;display:grid;place-items:center}.surface .webmpv-player{width:100%;height:100%;display:grid;place-items:center}.surface video,.surface canvas{max-width:100%;max-height:100%;object-fit:contain;width:100%;height:100%}.poster{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.empty{position:relative;text-align:center;padding:32px;color:#c1becb}.empty strong{display:block;color:var(--webmpv-foreground);font-size:20px;font-weight:550}.empty p{margin:8px 0 20px}.emblem{font-size:42px;color:var(--webmpv-accent);margin-bottom:12px}.controls{padding:8px 16px 14px}.timeline{width:100%;display:block}.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.time{font-variant-numeric:tabular-nums;color:#d7d4e0;white-space:nowrap}.space{flex:1}.volume{width:90px}.play{background:var(--webmpv-accent);color:#15121f;min-width:64px;border-color:transparent}.status{min-height:24px;padding:0 16px 10px;color:#c8c3d6;font-size:13px}.status:empty{display:none}.settings{position:absolute;z-index:3;right:12px;bottom:108px;max-width:calc(100% - 24px);width:320px;padding:18px;background:#202129;border:1px solid var(--webmpv-border);border-radius:12px;box-shadow:0 10px 60px #0009;max-height:65vh;overflow:auto}.settings header{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.settings label{display:grid;gap:5px;margin:12px 0}.settings select{width:100%}.notice{display:flex;align-items:center;gap:12px;padding:12px 16px;border-top:1px solid var(--webmpv-border);color:#f4d3d6}.notice span{flex:1}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.busy{position:absolute;top:16px;left:16px;padding:6px 12px;border-radius:20px;background:#16141ee8;color:#e4dbff}.file-actions{display:flex;gap:12px;flex-wrap:wrap}.file-actions label{display:inline-flex;margin:0}.help{font-size:12px;color:#c4becf}
:host(:fullscreen){background:#08090c;width:100%;height:100%}:host(:fullscreen) .shell{height:100%;border:0;border-radius:0;display:flex;flex-direction:column}:host(:fullscreen) .stage{flex:1;max-height:none;min-height:0;aspect-ratio:auto}:host(:fullscreen) .controls{flex:none}
@media(max-width:520px){.controls{padding:6px 10px 10px}.row{gap:6px}.volume{width:60px}.time{font-size:12px}.settings{bottom:140px}.stage{min-height:140px}.empty{padding:20px}.empty strong{font-size:17px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
@media(forced-colors:active){button,select,.shell,.settings{border:1px solid ButtonText}.play{background:ButtonFace;color:ButtonText}.stage{background:Canvas}.status,.empty,.time,.help{color:CanvasText}}
`;
